print('Olá, mundo!')
print('DESAFIO 01')
nome = input('Qual é o seu nome? ')
print('Olá, ', nome, '! Prazer em te conhecer!')
print('DESAFIO 02')
diaNasc = input('Que dia você nasceu? ')
mesNasc = input('Que mês você nasceu? ')
anoNasc = input('Que ano você nasceu? ')
print('Você nasceu no dia ', diaNasc, 'de ', mesNasc, 'de ', anoNasc, '.')
print('DESAFIO 03')
num1 = int(input('Primeiro número '))
num2 = int(input('Segundo número '))
soma = num1 + num2
print('A soma é', soma)
