frase = 'Curso em Vídeo Python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15:2])
print(frase[::2])
print(frase.count('o'))
print(frase.upper().count('O'))
print(frase)
frase = frase.upper()
print(frase)
print(len(frase))
frase = '   Curso em Vídeo Python   '
print(len(frase))
print(len(frase.strip()))
print(frase)
frase = frase.strip()
print(frase)
print(frase.replace('Python', 'Android'))
print('Curso' in frase)
print(frase.find('Curso'))
print(frase.find('Python'))
print(frase.find('vídeo'))
print(frase.lower().find('vídeo'))
print(frase.split())
dividido = frase.split()
print(dividido[3])
print(dividido[2][3])
